package com.tavant.jcxpmOutput

case class CompanyDetail()


case class Activity(co_ind_princ_sec:String,
co_junta_comer:String,
co_ramo_ativ:String,
co_seq_empresa:String,
co_sequencial:String,
de_ramo_ativ:String,
fl_manual_ramo_ativ:String,
fl_rev_qualidados_ramo_ativ:String)


case class Branch(co_cep:String,
co_cidade:String,
co_ind_gov:String,
co_junta_comer:String,
co_nat_jur:String,
co_pais:String,
co_porte:String,
co_seq_empresa:String,
co_sequencial:String,
co_situacaoemp:String,
co_tipo_arquiv:String,
co_tipo_dado:String,
co_tipo_moeda:String,
co_uf:String,
de_email:String,
de_ender_comp:String,
de_endereco:String,
de_nat_jur:String,
de_situacaoemp:String,
dt_constituicao:String,
dt_fim_ativ:String,
dt_ini_ativ:String,
dt_ultimo_arq:String,
fl_manual_nat_jur:String,
fl_manual_situacaoemp:String,
fl_manual_tp_moeda:String,
fl_rev_qualidados_nat_jur:String,
fl_rev_qualidados_situacaoemp:String,
fl_rev_qualidados_tp_moeda:String,
no_bairro:String,
no_cidade:String,
no_empresa:String,
  no_moeda:String,
nu_endereco:String,
nu_fax:String,
nu_inscr_estad:String,
nu_nire:String,
nu_nire_dados_cad_05:String,
nu_telefone:String,
nu_ultimo_arq:String,
vl_capital_soc:String)

case class CompanyComplimentaryData(co_alt_tipo_jur:String,
co_ind_cap_abert:String,
co_ind_cap_diver:String,
co_prazo_dura:String,
co_tipo_arquiv:String,
de_email:String,
dt_alt_tipo_jur:String,
dt_ins_capital:String,
dt_razao_ant:String,
dt_razao_soc:String,
no_empresa_ant:String,
nu_ano_recadas:String,
nu_nire:String,
nu_nire_dados_cad_17:String,
nu_recadastro:String)


case class PartnerCompany(co_condicao:String,
co_junta_comer:String,
co_seq_empresa:String,
co_seq_socio:String,
co_seq_socio_dados_cad:String,
co_sequencial:String,
co_tipo_arquiv:String,
co_tipo_arquiv_dados_cad:String,
co_tipo_moeda:String,
de_condicao:String,
dt_desligament:String,
dt_vinculacao:String,
fl_administrador:String,
fl_conselheiro:String,
fl_duplicate:Boolean,
fl_fiscal:String,
fl_manual_condicao:String,
fl_manual_moeda:String,
fl_rev_qualidados_condicao:String,
fl_rev_qualidados_moeda:String,
no_moeda:String,
no_pessoa_empresa:String,
nu_documento:String,
nu_documento_dados_cad:String,
nu_nire:String,
nu_nire_socio:String,
nu_nire_socio_dados_cad:String,
pe_participac:String,
vl_capital_soc:String)
case class PartnerComplimentaryData(
co_est_civil:String,
co_tipo_arquiv:String,
co_tipo_pess:String,
de_email:String,
de_org_exped:String,
de_reg_bens:String,
de_tp_doc:String,
de_tp_registro:String,
de_tp_socio:String,
nu_digito_doc:String,
nu_documento:String,
nu_nire:String,
nu_nire_socio:String,
nu_rg_rne:String,nu_seq_doc:String)


case class PartnerPerson(co_condicao:String,
co_dependente:String,
co_junta_comer:String,
co_seq_empresa:String,
co_seq_socio:String,
co_sequencial:String,
co_tipo_arquiv:String,
co_tipo_moeda:String,
de_condicao:String,
dt_desligament:String,
dt_termino_mandato:String,
dt_vinculacao:String,
fl_administrador:String,
fl_conselheiro:String,
fl_fiscal:String,
fl_manual_condicao:String,
fl_manual_moeda:String,
fl_rev_qualidados_condicao:String,
fl_rev_qualidados_moeda:String,
no_moeda:String,
nu_documento:String,
nu_nire:String,
pe_participac:String,
vl_capital_soc:String)
